'use strict';
console.log(`Run forest`);
console.log(`hii`);
console.log(`object`);
console.log(`I dunno man`);
console.log(`Dying at 24 I dunno man`);
console.log(`4 nisan`);
console.log(`x`);
console.log(`Hello world `);
console.log(`Hello world`);
console.log(`Do not matter`);
console.log(`object`);
console.log(`object`);
console.log(`Hello world`);
console.log(`hello world `);
console.log(`Hello world`);
