'use strict';
console.log(`Run forest`);
console.log(`hii`);
console.log(`object`);
console.log(`I dunno man`);
console.log(`Dying at 24 I dunno man`);
console.log(`4 nisan`);
console.log(`x`);
console.log(`Hello world `);
console.log(`Hello world`);
console.log(`Do not matter`);
console.log(`object`);
console.log(`object`);
console.log(`Hello world`);
console.log(`hello world `);
console.log(`Hello world`);
console.log(`Hello world`);
console.log(`Hello world`);
console.log(`2200.22.22`);
console.log(`hello world`);
console.log(`hello world`);
console.log(`xd`);
console.log(`jsk 19.20.20.19`);
console.log(`asdsa`);
console.log(`hi`);
