'use strict';
console.log(`hello world`);
console.log(`hello world again`);
console.log(`hello world`);
console.log(`do not disturb`);
console.log(`20 20 20`);
console.log(`hello`);
console.log(`literal`);
console.log(`literal`);
console.log(`hello world`);
